# Generated by Django 5.1.2 on 2024-12-16 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField(unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('sap_id', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offering_id', models.IntegerField(unique=True)),
                ('session', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to='offerings_media/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('sap_id', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to='attendance_media/')),
                ('description', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_no', models.IntegerField()),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='assignment_media/')),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('solution', models.FileField(upload_to='solution/')),
                ('best', models.FileField(upload_to='best/')),
                ('average', models.FileField(upload_to='average/')),
                ('worst', models.FileField(upload_to='worst/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to='assessments/')),
                ('solution', models.FileField(upload_to='solution/')),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('best', models.FileField(upload_to='best/')),
                ('average', models.FileField(upload_to='average/')),
                ('worst', models.FileField(upload_to='worst/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to='course_materials/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('outline_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='course_outline/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to='exam_media/')),
                ('solution', models.FileField(upload_to='solution/')),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('best', models.FileField(upload_to='best/')),
                ('average', models.FileField(upload_to='average/')),
                ('worst', models.FileField(upload_to='worst/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFaculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Gradesheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to='gradesheets/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to='lab_media/')),
                ('solution', models.FileField(upload_to='solution/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offering'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_no', models.IntegerField()),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='quiz_media/')),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('solution', models.FileField(upload_to='solution/')),
                ('best', models.FileField(upload_to='best/')),
                ('average', models.FileField(upload_to='average/')),
                ('worst', models.FileField(upload_to='worst/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
