# Generated by Django 5.1.2 on 2025-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_program_delete_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='path',
            field=models.CharField(default='default-path', max_length=100),
        ),
    ]
