# Generated by Django 5.1.2 on 2025-01-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_program_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_id',
        ),
    ]
