# Generated by Django 5.1.2 on 2025-01-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_program_program_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='offering_id',
        ),
    ]
