# Generated by Django 5.1.2 on 2025-01-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_offering_offering_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.program'),
        ),
    ]
