# Generated by Django 5.1.2 on 2025-01-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_offering_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutline',
            name='description',
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='name',
            field=models.CharField(default='Outline', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='average',
            field=models.FileField(blank=True, null=True, upload_to='average/'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='best',
            field=models.FileField(blank=True, null=True, upload_to='best/'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='assessments/'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to='solution/'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='worst',
            field=models.FileField(blank=True, null=True, upload_to='worst/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='average',
            field=models.FileField(blank=True, null=True, upload_to='average/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='best',
            field=models.FileField(blank=True, null=True, upload_to='best/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='assignment_media/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to='solution/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='worst',
            field=models.FileField(blank=True, null=True, upload_to='worst/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='attendance_media/'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='course_outline/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='average',
            field=models.FileField(blank=True, null=True, upload_to='average/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='best',
            field=models.FileField(blank=True, null=True, upload_to='best/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='exam_media/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to='solution/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='worst',
            field=models.FileField(blank=True, null=True, upload_to='worst/'),
        ),
        migrations.AlterField(
            model_name='gradesheet',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='gradesheets/'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='lab_media/'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to='solution/'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='offerings_media/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='average',
            field=models.FileField(blank=True, null=True, upload_to='average/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='best',
            field=models.FileField(blank=True, null=True, upload_to='best/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='quiz_media/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to='solution/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='worst',
            field=models.FileField(blank=True, null=True, upload_to='worst/'),
        ),
    ]
