# Generated by Django 5.1.2 on 2025-01-22 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_courseoutline_description_courseoutline_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.program'),
        ),
    ]
