# Generated by Django 5.1.2 on 2025-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_coursecategory_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='folder_name',
            field=models.CharField(default='course-name', max_length=100, unique=True),
        ),
    ]
