# Generated by Django 5.1.2 on 2025-02-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='course_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
