# Generated by Django 5.1.2 on 2025-02-15 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_coursecategory_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='media',
        ),
        migrations.CreateModel(
            name='CourseFolders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offering')),
            ],
        ),
    ]
