# Generated by Django 5.1.2 on 2025-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_coursecategory_image_remove_offering_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='folder_name',
        ),
        migrations.AddField(
            model_name='offering',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
