# Generated by Django 5.1.2 on 2025-02-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_course_folder_name_offering_ending_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='path',
        ),
        migrations.AddField(
            model_name='coursefolders',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='course_folders_taught', to='main.faculty'),
        ),
        migrations.AddField(
            model_name='coursefolders',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course_folders_enrolled', to='main.student'),
        ),
        migrations.AddField(
            model_name='program',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_as_hod', to='main.faculty'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('hod', 'Head of Department'), ('manager', 'Manager'), ('qch', 'Quality Control Head'), ('instructor', 'Instructor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gradesheet',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursefolders'),
        ),
        migrations.DeleteModel(
            name='CourseFaculty',
        ),
        migrations.DeleteModel(
            name='CourseStudent',
        ),
    ]
