# Generated by Django 5.1.2 on 2025-02-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_coursestudent_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='user_type',
            field=models.CharField(default='faculty', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='user_type',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
