# Generated by Django 5.1.2 on 2025-02-17 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_faculty_user_type_student_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursefolders',
            name='instructors',
        ),
        migrations.AddField(
            model_name='coursefolders',
            name='course_instructor',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coursefolders',
            name='lab_instructor',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='instructor',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='manager',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='qch',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='hod',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
