# Generated by Django 5.1.2 on 2025-02-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_coursefolders_instructors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefolders',
            name='course_instructor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursefolders',
            name='lab_instructor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='hod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='instructor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='manager',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='qch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
