# Generated by Django 5.1.2 on 2025-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_coursefolders_course_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
