# Generated by Django 5.1.2 on 2025-02-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_assignment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='media',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='courseoutline',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='media',
        ),
        migrations.RemoveField(
            model_name='gradesheet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='media',
        ),
        migrations.AddField(
            model_name='assessment',
            name='question',
            field=models.FileField(blank=True, null=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='question',
            field=models.FileField(blank=True, null=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question',
            field=models.FileField(blank=True, null=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='lab',
            name='question',
            field=models.FileField(blank=True, null=True, upload_to='question/'),
        ),
    ]
