# Generated by Django 5.1.2 on 2025-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_assessment_media_remove_assignment_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='media',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.FileField(blank=True, null=True, upload_to='question/'),
        ),
    ]
