# Generated by Django 5.1.2 on 2025-02-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_quiz_media_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='obtained_marks',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='obtained_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='obtained_marks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='obtained_marks',
        ),
    ]
